name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS Elastic Beanstalk CLI
        run: |
          sudo pip install awsebcli

      - name: Initialize EB CLI
        run: |
          eb init -p python-3.11 ${{
            secrets.EB_APP_NAME
          }} --region ${{ secrets.AWS_REGION }} \
          && eb use ${{ secrets.EB_ENV_NAME }}

      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy
